[project]
name = "checkers-on-stacks"
authors = []
description = "Decentralized Checkers/Draughts game on Stacks blockchain"
telemetry_enabled = false

[contracts.checkers]
path = "contracts/checkers.clar"
depends_on = ["checkers-leaderboard"]

[contracts.checkers-leaderboard]
path = "contracts/checkers-leaderboard.clar"

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[contracts.checkers-leaderboard]
path = 'contracts/checkers-leaderboard.clar'
clarity_version = 2
epoch = 2.4
