#!/bin/bash

echo "🚀 Mainnet Deployment via Hiro Platform"
echo "========================================"
echo ""
echo "Your mnemonic is configured in settings/Mainnet.toml"
echo ""
echo "📋 Steps to deploy:"
echo ""
echo "1. Go to: https://platform.hiro.so/"
echo ""
echo "2. Import wallet with this mnemonic:"
echo "   rare glow wheel hole illness undo split twelve skull awful dish install"
echo "   flower toy shock narrow lake immense ancient label barely unusual certain victory"
echo ""
echo "3. Switch to MAINNET"
echo ""
echo "4. Click 'Deploy Contract'"
echo ""
echo "5. Upload: contracts/checkers.clar"
echo ""
echo "6. Contract name: checkers"
echo ""
echo "7. Deploy (costs ~0.1 STX)"
echo ""
echo "✅ Contract compiles successfully (verified)"
echo ""
